#!/bin/sh

if [ -z "$1" ]; then
  echo -e "Usage: $0 package_name"
  exit 1
fi

if [ "$1" = "all" ]; then
  for script in *; do
    if [ -x "$script/create_addon" ]; then
      cd $script
      if [ "$?" = "0" ]; then
        ./create_addon
        if [ "$?" = "0" ]; then
          echo "$script: done\n"
        fi
        cd ../
      else
        echo "$script: an error occured\n"
      fi
    fi
  done
else
  cd $1
  if [ "$?" = "0" ]; then
    ./create_addon
    if [ "$?" = "0" ]; then
      echo "$1 done"; exit 0
    fi
  else
    echo "$1 does not exist"
    exit 1
  fi
fi
exit 0

