#!/bin/sh

cd tools/mkpkg
. ../../packages/3rdparty/download/Headphones/meta

echo "getting sources..."
  if [ ! -d build.Headphones.git ]; then
    git clone git://github.com/rembo10/headphones.git build.Headphones.git
  fi

  cd build.Headphones.git
    git checkout $PKG_VERSION
    GIT_REV=`git log -n1 --format=%h`
  cd ..

echo "copying sources..."
  rm -rf Headphones-$GIT_REV
  cp -R build.Headphones.git Headphones-$GIT_REV

echo "cleaning sources..."
  rm -rf Headphones-$GIT_REV/.git* Headphones-$GIT_REV/init* Headphones-$GIT_REV/TODO Headphones-$GIT_REV/README.md Headphones-$GIT_REV/COPYING Headphones-$GIT_REV/API_REFERENCE

echo "packing sources..."
  tar cJf Headphones-$GIT_REV.tar.xz Headphones-$GIT_REV

echo "remove temporary sourcedir..."
  rm -rf Headphones-$GIT_REV

echo "copying to dev folder"
  if [ ! -e /home/otkaz/Dropbox/Public/repository.lsellens/devel/Headphones-$GIT_REV.tar.xz ]; then
    cp Headphones-$GIT_REV.tar.xz /home/otkaz/Dropbox/Public/repository.lsellens/devel/; else
    echo "file exists"
  fi

echo "copying to source folder"
  cd ../../
  if [ ! -e sources/Headphones/Headphones-$GIT_REV.tar.xz ]; then
    mkdir -p sources/Headphones/
    mv tools/mkpkg/Headphones-$GIT_REV.tar.xz sources/Headphones/
    md5sum -t sources/Headphones/Headphones-$GIT_REV.tar.xz > sources/Headphones/Headphones-$GIT_REV.tar.xz.md5
    echo "http://dl.dropbox.com/u/42265484/repository.lsellens/devel/Headphones-$GIT_REV.tar.xz" > sources/Headphones/Headphones-$GIT_REV.tar.xz.url
    echo "done"; else
    echo "file exists"
  fi
