#!/bin/sh

. packages/3rdparty/download/SickBeard/meta
cd tools/mkpkg

echo "building $PKG_NAME..."
echo "getting sources..."
  if [ ! -d build.$PKG_NAME.git ]; then
    git clone $PKG_SITE.git build.$PKG_NAME.git
  fi

  cd build.$PKG_NAME.git
    git checkout ThePirateBay
    git pull
    git checkout $PKG_VERSION
    GIT_REV=`git log -n1 --format=%h`
  cd ..

  if [ ! -e ../../sources/$PKG_NAME/$PKG_NAME-$GIT_REV.tar.xz ]; then

    echo "copying sources..."
     rm -rf $PKG_NAME-$GIT_REV
     cp -R build.$PKG_NAME.git $PKG_NAME-$GIT_REV

    echo "cleaning sources..."
     rm -rf $PKG_NAME-$GIT_REV/.git* $PKG_NAME-$GIT_REV/.travis.yml $PKG_NAME-$GIT_REV/init.* $PKG_NAME-$GIT_REV/COPYING.txt $PKG_NAME-$GIT_REV/*.md $PKG_NAME-$GIT_REV/autoProcessTV/autoProcessTV.cfg.sample $PKG_NAME-$GIT_REV/setup.py $PKG_NAME-$GIT_REV/updater.py $PKG_NAME-$GIT_REV/googlecode_upload.py

    echo "packing sources..."
     tar cJf $PKG_NAME-$GIT_REV.tar.xz $PKG_NAME-$GIT_REV

    echo "remove temporary sourcedir..."
     rm -rf $PKG_NAME-$GIT_REV

    echo "copying to source folder"
     cd ../../
     mkdir -p sources/$PKG_NAME/
     mv tools/mkpkg/$PKG_NAME-$GIT_REV.tar.xz sources/$PKG_NAME/
     md5sum -t sources/$PKG_NAME/$PKG_NAME-$GIT_REV.tar.xz > sources/$PKG_NAME/$PKG_NAME-$GIT_REV.tar.xz.md5
     echo "$PKG_URL" > sources/$PKG_NAME/$PKG_NAME-$GIT_REV.tar.xz.url
    echo "done"; else
    echo "All ready at $GIT_REV. Skipping"
  fi
