#!/bin/sh

. config/options $1

if [ -z "$1" ]; then
  echo "usage: $0 package_name"
  exit 1
fi

unset INSTALL

mkdir -p $STAMPS/$1
STAMP=$STAMPS/$1/build

$SCRIPTS/unpack $1

if [ -f $STAMP -a -f $PKG_DIR/need_build ]; then
  $PKG_DIR/need_build $@
fi

if [ -f $STAMP -a $PKG_DIR/build -nt $STAMP ]; then
  rm -f $STAMP
fi

if [ ! -f $STAMP ]; then
  rm -f $STAMP

  printf "%${INDENT}c BUILD    $1\n" ' '>&$SILENT_OUT
  export INDENT=$((${INDENT:-1}+$INDENT_SIZE))

  for p in $PKG_BUILD_DEPENDS; do
    $SCRIPTS/build $p
  done

  echo "STAMP" >> $STAMP
fi
