#!/bin/sh

. config/options $1

[ -z "$PKG_URL" ] && exit 0

if [ -n "$PKG_URL" ]; then
tools/mkpkg/mkpkg_$1
  URLS="$URLS `echo $PKG_URL | sed s%GEEXBOX_SRCS%$GEEXBOX_SRCS%`"

  for i in $URLS; do
    SOURCE_NAME="`basename $i`"
    PACKAGE="$SOURCES/$1/$SOURCE_NAME"
    [ "$VERBOSE" != "yes" ] && WGET_OPT=-q
    WGET_CMD="wget --passive-ftp --no-check-certificate -c $WGET_OPT -P $SOURCES/$1"

    NBWGET="1"

    STAMP="$PACKAGE.url"
    MD5SUM="$PACKAGE.md5"

    mkdir -p $SOURCES/$1

    if [ -f "$STAMP" ]; then
      [ `cat $STAMP` = "$i" ] && continue
    fi
    DL="yes"

    rm -f $STAMP

    printf "%${INDENT}c GET      $1\n" ' '>&$SILENT_OUT
    export INDENT=$((${INDENT:-1}+$INDENT_SIZE))

    until [ -f "$STAMP" ] || $WGET_CMD $i; do
      NBWGET=$(($NBWGET+1))
      if [ "$NBWGET" -gt "10" ]; then
        echo -e "\nCant't get $1 sources : $i\n Try later !!"
        exit 1
      fi
    done

    echo $i > $STAMP
    md5sum -t $PACKAGE > $MD5SUM

    rm -f $BUILD_BASE*/$STAMPS_NOARCH/$1/unpack
    rm -f $BUILD_BASE*/$STAMPS_NOARCH/$1/build

  done
fi
