#!/bin/sh

. packages/unfs3/meta
cd mkpkg

echo "building $PKG_NAME..."
echo "getting sources..."
  if [ ! -d build.$PKG_NAME-$PKG_VERSION ]; then
    wget $PKG_URL
    if [ "$?" -ne "0" ]; then
      echo "error downloading source: $1";exit 1
    fi
    echo "extracting sources..."
    tar xzf $PKG_NAME-$PKG_VERSION.tar.gz
    if [ "$?" -ne "0" ]; then
      echo "error extracting source: $1";exit 1
    fi
    mv $PKG_NAME-$PKG_VERSION build.$PKG_NAME-$PKG_VERSION
    rm $PKG_NAME-$PKG_VERSION.tar.gz
  fi

echo "copying sources..."
  rm -rf $PKG_NAME-$PKG_VERSION
  cp -R build.$PKG_NAME-$PKG_VERSION $PKG_NAME-$PKG_VERSION

for i in patches/$PKG_NAME-*.patch; do
  if [ -f "$i" ]; then
    echo "patching sources..."
    echo $i
    cat $i | patch -p1 -d `echo "$PKG_NAME-$GIT_REV" | cut -f1 -d\ `
    if [ "$?" -ne "0" ]; then
      echo "error patching source: $1";exit 1
    fi
  fi
done

echo "configuring and compiling sources..."
   cd $PKG_NAME-$PKG_VERSION
   ./configure
   make
   make install prefix=$PWD
   make install-strip prefix=$PWD
   cd ../

echo "moving sources..."
  mv $PKG_NAME-$PKG_VERSION/sbin/unfsd ../build/script.service.unfsd/bin/unfsd && rm -rf $PKG_NAME-$PKG_VERSION
  if [ "$?" -ne "0" ]; then
    echo "error building $PKG_NAME: $1";exit 1
  fi

echo "done"
exit 0
